# Generated by Django 3.0.5 on 2020-04-07 19:19

import datetime
import json

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
from expenses.models import Category


def load_data(apps, schema_editor):
    f = open('expenses/json_file/expenses_category.json', 'r')
    json_data = json.load(f)

    for obj in json_data:
        if obj['name'] == 'category':
            for category in obj['data']:
                c = Category(
                    id=category['id'], name=category['name'], status=category['status'])
                c.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateTimeField()),
                ('merchant', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(
                    blank=True, null=True, upload_to='expenses/')),
                ('tax', models.FloatField(blank=True, null=True)),
                ('tip', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Category')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-updated', '-timestamp'],
            },
        ),
        migrations.RunPython(load_data),
    ]
