# Generated by Django 3.0.5 on 2020-04-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20200424_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='delete_on',
        ),
    ]
